sudo: false
language: ruby
rvm:
  - 2.4
script:
  - bundle exec jekyll build
  - bundle exec rake wax:proof
  - bundle exec rspec
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
