
language: ruby
rvm:
  - 2.4
script:
  - bundle exec jekyll build -d _site/wax
  - bundle exec htmlproofer ./_site --only-4xx --check-html --allow_hash_href --assume-extension  --disable-external --alt-ignore '/.*/'
  - bundle exec rspec
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
