title: Wax.
description: "a jekyll theme for minimal exhibitions"
baseurl: "/wax" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: pretty

exclude: [Gemfile*, node_modules, vendor]

collections:
  objects:
    output: true
    source: objects.csv
    key: id
    directory: objects
    layout: object-page

webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
