title: Wax.
description: "a jekyll theme for minimal exhibitions"
baseurl: ""
gh-baseurl: "/wax" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: pretty

exclude: [Gemfile*, node_modules, vendor]

collections:
  objects:
    source: objects.csv
    directory: objects
    layout: iiif-image-page

lunr:
  content: false
  name: lunr-index
  meta:
    - dir: objects
      fields:
        - pid
        - artist
        - location
        - title
        - _date
        - object_type
        - current_location

quoll:
  main:
    page: index.html
    terms:
      - iran
      - map
      - manuscript

webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
