# main settings
title:            Minicomp/Wax
description:      a jekyll theme for minimal exhibitions
url:              ''
baseurl:          '/wax'

# build settings
permalink:        pretty
lunr_language:    false
exclude:          [Gemfile*, node_modules, vendor, Rakefile, spec]
collections_dir:  collections

# wax collection settings
collections:
  pages:
    output:       true
  exhibits:
    output:       true
  qatar:
    output:       true
    keep_order:   true
    source:       qatar.csv
    layout:       iiif-image-page
    lunr_index:
      content:    false
      fields:
        - pid
        - title
        - artist
        - location
        - _date
        - object_type
        - current_location

# menu settings
menu:
  - label: About
    sub:
    - label: Wax
      link: /about/
    - label: Minicomp
      link: /minicomp/
    - label: Credits
      link: /credits/
  - label: Documentation
    link: /docs/
  - label: Exhibits
    link: /exhibits/
  - label: Gallery
    link: /gallery/

# search tests
quoll:
  main:
    page: '/'
    terms:
      - iran
      - map
      - manuscript

# cors headers for iiif use
webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
