title: Wax.
description: a jekyll theme for minimal exhibitions
url: ''
baseurl: '/wax'

# build settings
markdown: kramdown
permalink: pretty
lunr_language: false
exclude: [Gemfile*, node_modules, vendor, Rakefile]

# wax collection settings
collections:
  objects:
    output: true
    source: objects.csv
    layout: iiif-image-page
    lunr_index:
      content: false
      fields: [title, artist, location, _date, object_type, current_location]

# search tests
quoll:
  main:
    page: '/'
    terms: [iran, map, manuscript]

# cors headers for iiif use
webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
