# main settings
title:            Minicomp/Wax
description:      a jekyll theme for minimal exhibitions
url:              'https://mnyrop.github.io' # the url should stay empty
baseurl:          '/wax' # the baseurl of your site must be defined but can be an empty ''

# build settings
permalink:        'pretty'
exclude:          [Gemfile*, Rakefile, vendor, spec, README.md]
safe:             true

# wax collection settings
collections:
  qatar:
    output: true
    source: qatar.csv
    layout: qatar_item
    lunr_index:
      content: false
      fields: [pid, title, artist, location, _date, object_type, current_location]
    iiif:
      is_document: false
      sort: false
  book-of-horses:
    output: true
    iiif:
      is_document: true
      sort: true


# menu settings
menu:
  - label: About
    sub:
      - label: Wax
        link: /about/
      - label: Wiki Documentation
        link: 'https://minicomp.github.io/wiki/#/wax/'
      - label: Credits
        link: /credits
  - label: Components
    link: /components/
  - label: Tasks
    link: /tasks/
  - label: Exhibits
    link: /exhibits/
  - label: Browse
    link: /collection/
  - label: Search
    link: /search/

# search tests. run with $ bundle exec rspec
quoll:
  main:
    page: '/' # the path of the page you want to test
    terms:  # the search terms you expect to yield results
      - iran
      - map
      - manuscript

# javascript dependencies
js:
  jquery:
    version: 3.2.1
    cdn: //code.jquery.com/jquery-3.2.1.min.js
  popper:
    version: 1.12.9
    cdn: //cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js
  bootstrap:
    version: 4.0.0
    cdn: //maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js
  leaflet:
    version: 1.3.1
    cdn: //unpkg.com/leaflet@1.3.1/dist/leaflet.js
  leaflet-iiif:
    version: 2.0.1
    cdn: //cdn.jsdelivr.net/npm/leaflet-iiif@2.0.1/leaflet-iiif.min.js

# cors headers for iiif use
webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
