# main settings
title:            Minicomp/Wax
description:      a jekyll theme for minimal exhibitions
url:              ''
baseurl:          '/wax'

# build settings
permalink:        pretty
exclude:          [Gemfile*, Rakefile, node_modules, vendor, spec, README.md]
collections_dir:  collections

# wax collection settings
collections:
  qatar:
    output: true
    source: qatar.csv
    layout: iiif-image-page
    lunr_index:
      content: false
      fields: [pid, title, artist, location, _date, object_type, current_location]
    iiif:
      label: title

# menu settings
menu:
  - label: About
    sub:
    - label: Wax
      link: /about/
    - label: Minicomp
      link: /minicomp/
    - label: Credits
      link: /credits/
  - label: Documentation
    link: /docs/
  - label: Exhibits
    link: /exhibits/
  - label: Gallery
    link: /gallery/

# search tests
quoll:
  main:
    page: '/'
    terms:
      - iran
      - map
      - manuscript

# cors headers for iiif use
webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
