title: Wax.
description: a jekyll theme for minimal exhibitions
url: ''
baseurl: '/wax'

# build settings
markdown: kramdown
permalink: pretty
lunr_language: false
exclude: [Gemfile*, node_modules, vendor, Rakefile]

# wax collection settings
collections:
  objects:
    output: true
    source: objects.csv
    layout: iiif-image-page
    lunr_index:
      content: false
      fields: [title, artist, location, _date, object_type, current_location]

# js dependencies
js:
  openseadragon:
    version: 2.3.1
    cdn: https://cdnjs.cloudflare.com/ajax/libs/openseadragon/2.3.1/openseadragon.min.js
  jquery:
    version: 3.3.1
    cdn: https://code.jquery.com/jquery-3.2.1.slim.min.js
  elasticlunr:
    version: 0.9.6
    cdn: https://cdnjs.cloudflare.com/ajax/libs/elasticlunr/0.9.6/elasticlunr.min.js

# cors headers for iiif use
webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
